# Drawing Hello Kitty using the turtle library

import turtle as t

# for c in ['red', 'green', 'blue', 'yellow']:
#     t.color(c)
#     t.forward(75)
#     t.left(90)

t.shape("turtle")
t.color("black")
t.bgcolor("skyblue")
t.setup(600,600)
t.penup()
t.width(5)
t.goto(0,60)

def dcircle(size, filled):
    t.pendown()
    if filled:
        t.begin_fill()  
    t.setheading(180)  
    t.circle(size, 360)  
    if filled:
        t.end_fill()

def head():
  t.color("black","white")
  dcircle(75,True)
  t.penup()
  t.goto(40,60)
  t.color("black","white")
  dcircle(75,True)
  t.penup()
  t.goto(20,60)
  t.color("white","white")
  dcircle(75,True)
  t.penup()
  t.color("black")
  t.goto(37,60)
  t.pendown()
  t.forward(33)
  t.penup()
  t.color("black")
  t.goto(37,-90)
  t.pendown()
  t.forward(33)

def dcurvedtriangle(side1,side2,side3,filled):
  t.pendown()
  if filled:
      t.begin_fill()  
  t.forward(side1)
  t.right(20)
  t.forward(3)
  t.right(20)
  t.forward(2)
  t.right(20)
  t.forward(2)
  t.right(20)
  t.forward(2)
  t.right(20)
  t.forward(2)
  t.right(20)
  t.forward(side2)
  t.right(20)
  t.forward(2)
  t.right(20)
  t.forward(2)
  t.right(20)
  t.forward(2)
  t.right(20)
  t.forward(2)
  t.right(20)
  t.forward(2)
  t.right(20)
  t.forward(side3)
  t.right(20)
  t.forward(2)
  t.right(20)
  t.forward(2)
  t.right(20)
  t.forward(2)
  t.right(20)
  t.forward(2)
  t.right(20)
  t.forward(2)
  t.right(20)
  if filled:
    t.end_fill()

def ears():
  t.penup()
  t.color("black","white")
  t.right(40)
  t.goto(105,22)
  dcurvedtriangle(40,40,40,True)
  t.penup()
  t.goto(-30,50)
  t.left(80)
  dcurvedtriangle(40,40,40,True)
  t.color("white","white")
  t.forward(5)
  dcircle(20,True)

def bow():
  t.penup()
  t.goto(50,90)
  t.left(120)
  t.width(4)
  t.color("black","crimson")
  dcurvedtriangle(60,60,60,True)
  t.color("black")
  t.penup()
  t.forward(58)
  t.left(60)
  t.color("black","crimson")
  dcurvedtriangle(60,60,60,True)
  t.penup()
  t.right(2)
  t.forward(20)
  dcircle(14,True)
  t.penup()
  t.right(27)
  t.forward(50)
  dcircle(14,True)
  t.penup()
  t.goto(80,60)
  dcircle(23,True)

def eyes():
  t.penup()
  t.goto(-20,-30)
  t.width(3)
  t.color("black","black")
  dcircle(4,True)
  t.right(90)
  t.forward(3)
  dcircle(4,True)
  t.penup()
  t.backward(85)
  dcircle(4,True)
  t.left(90)
  t.forward(3)
  dcircle(4,True)

def nose():
  t.speed(1)
  t.penup()
  t.goto(20,-50)
  t.color("black","yellow")
  dcircle(5,True)
  t.penup()
  t.left(90)
  t.forward(2)
  t.right(90)
  t.forward(4)
  t.right(90)
  t.forward(2)
  t.left(90)
  dcircle(5,True)
  t.color("yellow")
  t.penup()
  t.left(90)
  t.forward(4)
  t.right(90)
  t.pendown()
  t.width(5)
  t.backward(4)
  t.penup()
  t.goto(0,0)

def whiskers():
  t.penup()
  t.goto(-55,-27)
  t.pendown()
  t.color("black")
  t.width(4)
  t.goto(-100,-24)
  t.penup()
  t.goto(-56,-40)
  t.pendown()
  t.goto(-95,-48)
  t.penup()
  t.goto(-54,-56)
  t.pendown()
  t.goto(-98,-68)
  t.penup()
  t.goto(95,-27)
  t.pendown()
  t.goto(130,-23)
  t.penup()
  t.goto(96,-40)
  t.pendown()
  t.goto(127,-47)
  t.penup()
  t.goto(94,-57)
  t.pendown()
  t.goto(128,-73)
  
head()
ears()
bow()
eyes()
nose()
whiskers()

t.hideturtle()
t.done()